#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /openapi.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
